[phases.release]
cmd = "php artisan migrate --force && php artisan cache:clear && php artisan config:clear && php artisan route:clear && php artisan view:clear"

[build]
cmds = ["composer install --no-dev"]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/"
