DocumentRoot public/

# Disable .htaccess parsing completely
<Directory public>
  AllowOverride None
</Directory>

# Add support for Laravel routing
<IfModule mod_rewrite.c>
  <Directory public>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} -f
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^ - [QSA,L]
    RewriteRule ^ index.php [QSA,L]
  </Directory>
</IfModule>
